[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.marketing.subscriptions"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "marketing", "subscriptions"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.marketing.subscriptions"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
